name: Chart Releaser

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'
  workflow_dispatch:


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
